### ISSUE TITLE
It's not downloading

### ISSUE THREAD

**Issue by thany** [GlossyPanther/Reddit-Downloader#2]
I set the root directory and added a subreddit with pictures. I also enabled NSFW. And then... There's nothing to do. No confident Start button or anything. Supposedly magic should now happen.

But it doesn;t.

Nothing is happening. At least nothing is getting downloaded to the directory I told it to use. I'm not sure if it's putting images anywhere else though.

**Comment by chazragg** [comment]
Hi thany, sorry to hear you are having issue with the program.

the general process is to add a subreddit and then when you save pictures within that subreddit the program will detect this and automatically download them for you.

if you are doing this and still cannot see the pictures do you have hidden folders turned on? the NSFW option will hide the folder from regular explorer view.

![image](https://user-images.githubusercontent.com/4650060/31591288-08ff0b90-b216-11e7-8eed-c0c2b0d0a784.png)

here is a picture of how to enable the option in windows 10 if you do not already have it enabled.


if the two suggestions above do not work then it would be helpful to know where the images are hosted, are they uploaded to Reddit or imgur ? or do they take you to another sites once clicked ? as the program currently only works with images hosted by imgur or Reddit it's self.

if you provide the subreddit you are trying to download from i will perform some tests to see if i can narrow down the issue if non of the above work.

**Comment by thany** [comment]
Hidden files/folders aren't the problem. I use total commander, which I've set up to always show absolutely everything :B

I haven't checked where the images lead, and as I'm at work right now I shouldn't check, because the subreddit is NSFW. Just for fun, I was trying the program out with r/petite :X

**Comment by GlossyPanther** [comment]
Hi, if you could attach a screenshot of the settings when you’re next able to it would really help me pinpoint the issue. It sounds like either the path hadn’t been set correctly or the download hadn’t started yet. The program checks periodically and may not start right away.
